{% set name = "three.js" %}
{% set version = "122" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrdoob/three.js/archive/r{{ version }}.tar.gz
  sha256: eeed366444ff521cfa0f3f97a33dea6adefb8a3111617dc1599df83722bcd56a

build:
  number: 1
  noarch: generic
  script: |
    cat $RECIPE_DIR/sage.js >> src/Three.js
    tgz=$(npm pack)
    npm install -g $tgz
    mkdir -p $PREFIX/share
    mv $PREFIX/lib/node_modules/three $PREFIX/share/threejs
    ln -s $PREFIX/share/threejs $PREFIX/lib/node_modules/three
    echo "$PKG_VERSION" > $PREFIX/share/threejs/version

requirements:
  build:
    - nodejs

test:
  commands:
    - test -f $PREFIX/share/threejs/build/three.min.js  # [unix]

about:
  home: https://threejs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JavaScript 3D library.
  dev_url: https://github.com/mrdoob/three.js

extra:
  recipe-maintainers:
    - isuruf
