{% set name = "three.js" %}
{% set version = "106" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrdoob/three.js/archive/r{{ version }}.tar.gz
  sha256: c5cf0483a808ee5f33f27cc5b92b67de72a4efb839f806454c7ca5011395fab1

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - test -f $PREFIX/lib/node_modules/three/build/three.min.js  # [unix]

about:
  home: https://threejs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'JavaScript 3D library.'
  dev_url: https://github.com/mrdoob/three.js

extra:
  recipe-maintainers:
    - isuruf
